name: train_de_mots
description: Jeu de mots pour animer des soirées entre amis sur Twitch
publish_to: 'none' 
version: 1.7.3+1

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  diacritic: ^0.1.4
  twitch_manager:
  collection: ^1.17.2
  audioplayers: ^6.6.0
  flutter_colorpicker: ^1.0.3
  shared_preferences: ^2.2.0
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  cloud_firestore: ^6.1.0
  url_launcher: ^6.2.5
  http: ^1.2.1
  mutex: ^3.1.0
  logging: ^1.2.0
  web: ^1.1.1
  common: 
    path: ../common
  vector_math: ^2.1.4
  flutter_localizations:
    sdk: flutter

dependency_overrides:
  twitch_manager:
    path: ../common/plugins/twitch_manager

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/youtube_logo.png

    - assets/sounds/BestSolutionFound.mp3
    - assets/sounds/GameStarted.mp3
    - assets/sounds/GoldenSolutionAppeared.mp3
    - assets/sounds/LettersScrambling.mp3
    - assets/sounds/RoundIsOver.mp3
    - assets/sounds/SolutionFound.mp3
    - assets/sounds/SolutionStolen.mp3
    - assets/sounds/NewBoostGranted.mp3
    - assets/sounds/TelegramReceived.mp3
    - assets/sounds/TheSwindler.mp3
    - assets/sounds/TrainLostStation.mp3
    - assets/sounds/TrainReachedStation.mp3
    - assets/sounds/Fireworks1.mp3
    - assets/sounds/Fireworks2.mp3
    - assets/sounds/Fireworks3.mp3
    - assets/sounds/Fireworks4.mp3
    - assets/sounds/Fireworks5.mp3
    - assets/sounds/Fireworks6.mp3
    - assets/sounds/TheBigHeist.mp3
    - assets/sounds/BigHeistSuccess.mp3
    - assets/sounds/BigHeistFailed.mp3
    - assets/sounds/ChangingLane.mp3

    - assets/sounds/treasure_hunt/picking_treasure.mp3
    - assets/sounds/treasure_hunt/pluck_grass1.mp3 
    - assets/sounds/treasure_hunt/pluck_grass2.mp3 
    - assets/sounds/treasure_hunt/pluck_grass3.mp3
    - assets/sounds/treasure_hunt/pluck_grass4.mp3 

    - assets/sounds/blueberry_war/letter_hit.mp3
    - assets/sounds/blueberry_war/letter_knock.mp3

    - assets/sounds/warehouse_cleaning/avatar_launched1.mp3
    - assets/sounds/warehouse_cleaning/avatar_launched2.mp3
    - assets/sounds/warehouse_cleaning/avatar_launched3.mp3
    - assets/sounds/warehouse_cleaning/avatar_launched4.mp3