name: video_component
description: "Implementation of the video_component of the frontend"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  logging: ^1.2.0
  frontend_common:
    path: ../frontend_common
  common:
    path: ../../common
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - packages/common/assets/images/train.png

  fonts:
    - family: BaskervvilleSC
      fonts:
        - asset: packages/common/assets/fonts/BaskervvilleSC/BaskervvilleSC-Regular.ttf
