name: common
description: Common things to share between the EBS server, the App and the Frontend
version: 1.0.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  logging: ^1.2.0
  shared_preferences: ^2.2.0
  collection: ^1.18.0
  diacritic: ^0.1.4
  vector_math: ^2.1.4
  crypto: ^3.0.7

dev_dependencies:
  lints: ^6.0.0
  test: ^1.24.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/train.png
    - assets/images/parchment.png

    - assets/images/treasure_hunt/blueberries.png
    - assets/images/treasure_hunt/grass.png
    - assets/images/treasure_hunt/open_grass.png

    - assets/images/blueberry_war/blueberries.png

    - assets/images/warehouse_cleaning/box.png
    - assets/images/warehouse_cleaning/floor.png

    - assets/images/track_fix/grass.png
    - assets/images/track_fix/open_grass.png

  fonts:
    - family: BaskervvilleSC
      fonts:
        - asset: assets/fonts/BaskervvilleSC/BaskervvilleSC-Regular.ttf
    - family: MedievalSharp
      fonts:
        - asset: assets/fonts/MedievalSharp/MedievalSharp-Regular.ttf
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/Roboto.woff2  
